apiVersion: autoscaling/v2  
kind: HorizontalPodAutoscaler
metadata:
  name: aspnetapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aspnetapp
  minReplicas: 1              
  maxReplicas: 5             
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90  # Target CPU utilization percentage
