apiVersion: v1
kind: Service
metadata:
  name: aspnetapp
  labels:
    app: aspnetapp
spec:
  type: LoadBalancer
  ports:
  - port: 80          # The port that the service will expose
    targetPort: 8080  # The port that the application is listening on
  selector:
    app: aspnetapp
